package comp31.ass2.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.NoArgsConstructor;
/*
 * Author: Manlin Mao
 * Date: 2023-12-06
 *
 * Class/File: PetPreferences.java
 *
 * Additional context:
 * This Java class defines the entity "PetPreferences," which represents the preferred characteristics
 * of a pet according to a pet owner's preferences. The class is annotated with JPA annotations for
 * persistence mapping and includes fields such as id, preferredSpecies, preferredColor, and preferredSize.
 *
 * The class provides a constructor to initialize the preferences with specific values. Instances of
 * "PetPreferences" are associated with instances of the "PetOwner" entity through a one-to-one relationship,
 * established by the foreign key "fkey_pet_preferences" in the "PetOwner" entity.
 *
 * The class includes standard annotations generated by Lombok for data encapsulation and a no-argument
 * constructor. Instances of this class can be used to store and retrieve a pet owner's preferred species,
 * color, and size for pets.
 */

@Entity
@Data
@NoArgsConstructor
public class PetPreferences {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Integer id;
    String preferredSpecies;
    String preferredColor;
    String preferredSize;

    public PetPreferences(String preferredSpecies, String preferredColor, String preferredSize) {
        this.preferredSpecies = preferredSpecies;
        this.preferredColor = preferredColor;
        this.preferredSize = preferredSize;
    }

}
